//! EFX reverb presets (transcribed from `efx-presets.h`).
//!
//! Donor provenance: `src/audio/reverb-presets.ts`. Generated from the donor table.

/// EFX reverb parameters.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EfxReverbParams {
    /// `density`.
    pub density: f64,
    /// `diffusion`.
    pub diffusion: f64,
    /// `gain`.
    pub gain: f64,
    /// `gainHF`.
    pub gain_hf: f64,
    /// `gainLF`.
    pub gain_lf: f64,
    /// `decayTime`.
    pub decay_time: f64,
    /// `decayHFRatio`.
    pub decay_hf_ratio: f64,
    /// `decayLFRatio`.
    pub decay_lf_ratio: f64,
    /// `reflectionsGain`.
    pub reflections_gain: f64,
    /// `reflectionsDelay`.
    pub reflections_delay: f64,
    /// `lateReverbGain`.
    pub late_reverb_gain: f64,
    /// `lateReverbDelay`.
    pub late_reverb_delay: f64,
    /// `echoTime`.
    pub echo_time: f64,
    /// `echoDepth`.
    pub echo_depth: f64,
    /// `modulationTime`.
    pub modulation_time: f64,
    /// `modulationDepth`.
    pub modulation_depth: f64,
    /// `airAbsorptionGainHF`.
    pub air_absorption_gain_hf: f64,
    /// `hfReference`.
    pub hf_reference: f64,
    /// `lfReference`.
    pub lf_reference: f64,
    /// `roomRolloffFactor`.
    pub room_rolloff_factor: f64,
    /// `decayHFLimit`.
    pub decay_hf_limit: bool,
}

/// Preset names in preset-id order.
pub const REVERB_PRESET_NAMES: [&str; 26] = [
    "generic",
    "padded_cell",
    "room",
    "bathroom",
    "living_room",
    "stone_room",
    "auditorium",
    "concert_hall",
    "cave",
    "arena",
    "hangar",
    "carpeted_hallway",
    "hallway",
    "stone_corridor",
    "alley",
    "forest",
    "city",
    "mountains",
    "quarry",
    "plain",
    "parking_lot",
    "sewer_pipe",
    "underwater",
    "drugged",
    "dizzy",
    "psychotic",
];

/// Fallback preset id (`plain`).
pub const REVERB_PRESET_PLAIN: usize = 19;

/// Presets in [`REVERB_PRESET_NAMES`] order.
pub const REVERB_PRESETS: [EfxReverbParams; 26] = [
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.8913,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.83,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.05,
        reflections_delay: 0.007,
        late_reverb_gain: 1.2589,
        late_reverb_delay: 0.011,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 0.1715,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.001,
        gain_lf: 1.0,
        decay_time: 0.17,
        decay_hf_ratio: 0.1,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.25,
        reflections_delay: 0.001,
        late_reverb_gain: 1.2691,
        late_reverb_delay: 0.002,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 0.4287,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.5929,
        gain_lf: 1.0,
        decay_time: 0.4,
        decay_hf_ratio: 0.83,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.1503,
        reflections_delay: 0.002,
        late_reverb_gain: 1.0629,
        late_reverb_delay: 0.003,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 0.1715,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.2512,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.54,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.6531,
        reflections_delay: 0.007,
        late_reverb_gain: 3.2734,
        late_reverb_delay: 0.011,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 0.9766,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.001,
        gain_lf: 1.0,
        decay_time: 0.5,
        decay_hf_ratio: 0.1,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.2051,
        reflections_delay: 0.003,
        late_reverb_gain: 0.2805,
        late_reverb_delay: 0.004,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.7079,
        gain_lf: 1.0,
        decay_time: 2.31,
        decay_hf_ratio: 0.64,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.4411,
        reflections_delay: 0.012,
        late_reverb_gain: 1.1003,
        late_reverb_delay: 0.017,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.5781,
        gain_lf: 1.0,
        decay_time: 4.32,
        decay_hf_ratio: 0.59,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.4032,
        reflections_delay: 0.02,
        late_reverb_gain: 0.717,
        late_reverb_delay: 0.03,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.5623,
        gain_lf: 1.0,
        decay_time: 3.92,
        decay_hf_ratio: 0.7,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.2427,
        reflections_delay: 0.02,
        late_reverb_gain: 0.9977,
        late_reverb_delay: 0.029,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 1.0,
        gain_lf: 1.0,
        decay_time: 2.91,
        decay_hf_ratio: 1.3,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.5,
        reflections_delay: 0.015,
        late_reverb_gain: 0.7063,
        late_reverb_delay: 0.022,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: false,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.4477,
        gain_lf: 1.0,
        decay_time: 7.24,
        decay_hf_ratio: 0.33,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.2612,
        reflections_delay: 0.02,
        late_reverb_gain: 1.0186,
        late_reverb_delay: 0.03,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.3162,
        gain_lf: 1.0,
        decay_time: 10.05,
        decay_hf_ratio: 0.23,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.5,
        reflections_delay: 0.02,
        late_reverb_gain: 1.256,
        late_reverb_delay: 0.03,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 0.4287,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.01,
        gain_lf: 1.0,
        decay_time: 0.3,
        decay_hf_ratio: 0.1,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.1215,
        reflections_delay: 0.002,
        late_reverb_gain: 0.1531,
        late_reverb_delay: 0.03,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 0.3645,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.7079,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.59,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.2458,
        reflections_delay: 0.007,
        late_reverb_gain: 1.6615,
        late_reverb_delay: 0.011,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.7612,
        gain_lf: 1.0,
        decay_time: 2.7,
        decay_hf_ratio: 0.79,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.2472,
        reflections_delay: 0.013,
        late_reverb_gain: 1.5758,
        late_reverb_delay: 0.02,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 0.3,
        gain: 0.3162,
        gain_hf: 0.7328,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.86,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.25,
        reflections_delay: 0.007,
        late_reverb_gain: 0.9954,
        late_reverb_delay: 0.011,
        echo_time: 0.125,
        echo_depth: 0.95,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 0.3,
        gain: 0.3162,
        gain_hf: 0.0224,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.54,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.0525,
        reflections_delay: 0.162,
        late_reverb_gain: 0.7682,
        late_reverb_delay: 0.088,
        echo_time: 0.125,
        echo_depth: 1.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 0.5,
        gain: 0.3162,
        gain_hf: 0.3981,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.67,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.073,
        reflections_delay: 0.007,
        late_reverb_gain: 0.1427,
        late_reverb_delay: 0.011,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 0.27,
        gain: 0.3162,
        gain_hf: 0.0562,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.21,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.0407,
        reflections_delay: 0.3,
        late_reverb_gain: 0.1919,
        late_reverb_delay: 0.1,
        echo_time: 0.25,
        echo_depth: 1.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: false,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.3162,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.83,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.0,
        reflections_delay: 0.061,
        late_reverb_gain: 1.7783,
        late_reverb_delay: 0.025,
        echo_time: 0.125,
        echo_depth: 0.7,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 0.21,
        gain: 0.3162,
        gain_hf: 0.1,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.5,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.0585,
        reflections_delay: 0.179,
        late_reverb_gain: 0.1089,
        late_reverb_delay: 0.1,
        echo_time: 0.25,
        echo_depth: 1.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 1.0,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 1.0,
        gain_lf: 1.0,
        decay_time: 1.65,
        decay_hf_ratio: 1.5,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.2082,
        reflections_delay: 0.008,
        late_reverb_gain: 0.2652,
        late_reverb_delay: 0.012,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: false,
    },
    EfxReverbParams {
        density: 0.3071,
        diffusion: 0.8,
        gain: 0.3162,
        gain_hf: 0.3162,
        gain_lf: 1.0,
        decay_time: 2.81,
        decay_hf_ratio: 0.14,
        decay_lf_ratio: 1.0,
        reflections_gain: 1.6387,
        reflections_delay: 0.014,
        late_reverb_gain: 3.2471,
        late_reverb_delay: 0.021,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 0.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 0.3645,
        diffusion: 1.0,
        gain: 0.3162,
        gain_hf: 0.01,
        gain_lf: 1.0,
        decay_time: 1.49,
        decay_hf_ratio: 0.1,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.5963,
        reflections_delay: 0.007,
        late_reverb_gain: 7.0795,
        late_reverb_delay: 0.011,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 1.18,
        modulation_depth: 0.348,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: true,
    },
    EfxReverbParams {
        density: 0.4287,
        diffusion: 0.5,
        gain: 0.3162,
        gain_hf: 1.0,
        gain_lf: 1.0,
        decay_time: 8.39,
        decay_hf_ratio: 1.39,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.876,
        reflections_delay: 0.002,
        late_reverb_gain: 3.1081,
        late_reverb_delay: 0.03,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 0.25,
        modulation_depth: 1.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: false,
    },
    EfxReverbParams {
        density: 0.3645,
        diffusion: 0.6,
        gain: 0.3162,
        gain_hf: 0.631,
        gain_lf: 1.0,
        decay_time: 17.23,
        decay_hf_ratio: 0.56,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.1392,
        reflections_delay: 0.02,
        late_reverb_gain: 0.4937,
        late_reverb_delay: 0.03,
        echo_time: 0.25,
        echo_depth: 1.0,
        modulation_time: 0.81,
        modulation_depth: 0.31,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: false,
    },
    EfxReverbParams {
        density: 0.0625,
        diffusion: 0.5,
        gain: 0.3162,
        gain_hf: 0.8404,
        gain_lf: 1.0,
        decay_time: 7.56,
        decay_hf_ratio: 0.91,
        decay_lf_ratio: 1.0,
        reflections_gain: 0.4864,
        reflections_delay: 0.02,
        late_reverb_gain: 2.4378,
        late_reverb_delay: 0.03,
        echo_time: 0.25,
        echo_depth: 0.0,
        modulation_time: 4.0,
        modulation_depth: 1.0,
        air_absorption_gain_hf: 0.9943,
        hf_reference: 5000.0,
        lf_reference: 250.0,
        room_rolloff_factor: 0.0,
        decay_hf_limit: false,
    },
];

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn presets_line_up() {
        assert_eq!(REVERB_PRESET_NAMES.len(), REVERB_PRESETS.len());
        assert_eq!(REVERB_PRESET_NAMES[REVERB_PRESET_PLAIN], "plain");
        assert!(REVERB_PRESETS[0].decay_time - 1.49 < 1e-12);
        assert!(REVERB_PRESETS.iter().all(|preset| preset.density > 0.0));
    }
}
