[package]
name = "qa-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
proof = []
allocation-tracking = ["qa-console/lookup-tracking"]

[dependencies]
qa-core = { path = "../core" }

[dev-dependencies]
qa-input = { path = "../input" }
qa-network = { path = "../network" }
qa-app = { path = "../app" }
qa-console = { path = "../console" }
qa-session = { path = "../session" }
