// Generated by tools/generate_cvars.py from the unified cvar catalog.
// R0 registers developer; R2 adds the remaining catalog and string-valued cvars.
use crate::cvars::Definition;

pub static DEFINITIONS: &[Definition] = &[Definition {
    name: "developer",
    aliases: &[],
    default: 0.0,
}];
