//! Native runtime imports resolved at load and executed only in the owned child.
use super::NativeScalar;

pub const FIRST: u32 = 0x8000_0000;
pub struct Function {
    pub name: &'static [u8],
    pub number: u32,
    pub heap: bool,
    pub provider: &'static [u8],
    pub versions: &'static [&'static [u8]],
    pub parameters: &'static [NativeScalar],
    pub result: NativeScalar,
    pub(crate) operation: Operation,
}
use NativeScalar::{Double, I32, Void, Word};
const LIBC: &[u8] = b"libc.so.6";
const LIBM: &[u8] = b"libm.so.6";
const BASE_VERSION: &[&[u8]] = &[b"GLIBC_2.2.5"];
pub const FUNCTIONS: &[Function] = &[
    Function {
        name: b"memcpy",
        heap: false,
        provider: LIBC,
        versions: &[b"GLIBC_2.2.5", b"GLIBC_2.14"],
        number: FIRST,
        parameters: &[Word, Word, Word],
        result: Word,
        operation: Operation::Copy,
    },
    Function {
        name: b"memmove",
        heap: false,
        provider: LIBC,
        versions: BASE_VERSION,
        number: FIRST,
        parameters: &[Word, Word, Word],
        result: Word,
        operation: Operation::Copy,
    },
    Function {
        name: b"memset",
        heap: false,
        provider: LIBC,
        versions: BASE_VERSION,
        number: FIRST + 1,
        parameters: &[Word, I32, Word],
        result: Word,
        operation: Operation::Fill,
    },
    Function {
        name: b"strncpy",
        heap: false,
        provider: LIBC,
        versions: BASE_VERSION,
        number: FIRST + 2,
        parameters: &[Word, Word, Word],
        result: Word,
        operation: Operation::Strncpy,
    },
    Function {
        name: b"strlen",
        heap: false,
        provider: LIBC,
        versions: BASE_VERSION,
        number: FIRST + 3,
        parameters: &[Word],
        result: Word,
        operation: Operation::Length,
    },
    Function {
        name: b"strcmp",
        heap: false,
        provider: LIBC,
        versions: BASE_VERSION,
        number: FIRST + 4,
        parameters: &[Word, Word],
        result: I32,
        operation: Operation::CompareString,
    },
    Function {
        name: b"memcmp",
        heap: false,
        provider: LIBC,
        versions: BASE_VERSION,
        number: FIRST + 5,
        parameters: &[Word, Word, Word],
        result: I32,
        operation: Operation::CompareMemory,
    },
    Function {
        name: b"sin",
        number: FIRST + 6,
        heap: false,
        provider: LIBM,
        versions: BASE_VERSION,
        parameters: &[Double],
        result: Double,
        operation: Operation::Sin,
    },
    Function {
        name: b"cos",
        number: FIRST + 7,
        heap: false,
        provider: LIBM,
        versions: BASE_VERSION,
        parameters: &[Double],
        result: Double,
        operation: Operation::Cos,
    },
    Function {
        name: b"atan2",
        number: FIRST + 8,
        heap: false,
        provider: LIBM,
        versions: BASE_VERSION,
        parameters: &[Double, Double],
        result: Double,
        operation: Operation::Atan2,
    },
    Function {
        name: b"sqrt",
        number: FIRST + 9,
        heap: false,
        provider: LIBM,
        versions: BASE_VERSION,
        parameters: &[Double],
        result: Double,
        operation: Operation::Sqrt,
    },
    Function {
        name: b"floor",
        number: FIRST + 10,
        heap: false,
        provider: LIBM,
        versions: BASE_VERSION,
        parameters: &[Double],
        result: Double,
        operation: Operation::Floor,
    },
    Function {
        name: b"ceil",
        number: FIRST + 11,
        heap: false,
        provider: LIBM,
        versions: BASE_VERSION,
        parameters: &[Double],
        result: Double,
        operation: Operation::Ceil,
    },
    Function {
        name: b"acos",
        number: FIRST + 12,
        heap: false,
        provider: LIBM,
        versions: BASE_VERSION,
        parameters: &[Double],
        result: Double,
        operation: Operation::Acos,
    },
    Function {
        name: b"fabs",
        number: FIRST + 13,
        heap: false,
        provider: LIBM,
        versions: BASE_VERSION,
        parameters: &[Double],
        result: Double,
        operation: Operation::Absolute,
    },
    Function {
        name: b"malloc",
        number: FIRST + 14,
        heap: true,
        provider: LIBC,
        versions: BASE_VERSION,
        parameters: &[Word],
        result: Word,
        operation: Operation::Malloc,
    },
    Function {
        name: b"calloc",
        number: FIRST + 15,
        heap: true,
        provider: LIBC,
        versions: BASE_VERSION,
        parameters: &[Word, Word],
        result: Word,
        operation: Operation::Calloc,
    },
    Function {
        name: b"realloc",
        number: FIRST + 16,
        heap: true,
        provider: LIBC,
        versions: BASE_VERSION,
        parameters: &[Word, Word],
        result: Word,
        operation: Operation::Realloc,
    },
    Function {
        name: b"free",
        number: FIRST + 17,
        heap: true,
        provider: LIBC,
        versions: BASE_VERSION,
        parameters: &[Word],
        result: Void,
        operation: Operation::Free,
    },
];

#[derive(Clone, Copy)]
pub(crate) enum Operation {
    Copy,
    Fill,
    Strncpy,
    Length,
    CompareString,
    CompareMemory,
    Sin,
    Cos,
    Atan2,
    Sqrt,
    Floor,
    Ceil,
    Acos,
    Absolute,
    Malloc,
    Calloc,
    Realloc,
    Free,
}

pub fn function(number: u32) -> Option<&'static Function> {
    FUNCTIONS.iter().find(|f| f.number == number)
}
#[derive(Clone, Copy, Debug)]
pub struct RuntimeConfig {
    pub base: u64,
    pub heap_bytes: usize,
}
