//! Base weapon definitions (`src/content/q2/foundation/weapons/definitions.ts`).

use super::types::{Q2BaseWeaponDefinition, Q2BaseWeaponName, Q2WeaponDefinition};

fn definition(
    name: Q2BaseWeaponName,
    item: &str,
    classname: &str,
    ammo: Option<&str>,
    quantity: i32,
    warning: i32,
    view_model: &str,
    world_model: &str,
    player_model: i32,
    activate_last: i32,
    fire_last: i32,
    idle_last: i32,
    deactivate_last: i32,
    pauses: Vec<i32>,
    fires: Vec<i32>,
    repeating: bool,
) -> Q2BaseWeaponDefinition {
    Q2BaseWeaponDefinition {
        name,
        definition: Q2WeaponDefinition {
            name: name.as_str().to_string(),
            item: item.to_string(),
            classname: classname.to_string(),
            ammo: ammo.map(str::to_string),
            quantity,
            warning,
            view_model: view_model.to_string(),
            world_model: world_model.to_string(),
            player_model,
            activate_last,
            fire_last,
            idle_last,
            deactivate_last,
            pauses,
            fires,
            repeating,
        },
    }
}

/// Base weapon definitions (`Q2_BASE_WEAPONS`).
pub fn base_weapons() -> Vec<Q2BaseWeaponDefinition> {
    vec![
        definition(
            Q2BaseWeaponName::Blaster,
            "q2:weapon_blaster",
            "weapon_blaster",
            None,
            0,
            0,
            "models/weapons/v_blast/tris.md2",
            "",
            1,
            4,
            8,
            52,
            55,
            vec![19, 32],
            vec![5],
            false,
        ),
        definition(
            Q2BaseWeaponName::Shotgun,
            "q2:weapon_shotgun",
            "weapon_shotgun",
            Some("q2:ammo_shells"),
            1,
            5,
            "models/weapons/v_shotg/tris.md2",
            "models/weapons/g_shotg/tris.md2",
            2,
            7,
            18,
            36,
            39,
            vec![22, 28, 34],
            vec![8, 9],
            false,
        ),
        definition(
            Q2BaseWeaponName::Supershotgun,
            "q2:weapon_supershotgun",
            "weapon_supershotgun",
            Some("q2:ammo_shells"),
            2,
            10,
            "models/weapons/v_shotg2/tris.md2",
            "models/weapons/g_shotg2/tris.md2",
            3,
            6,
            17,
            57,
            61,
            vec![29, 42, 57],
            vec![7],
            false,
        ),
        definition(
            Q2BaseWeaponName::Machinegun,
            "q2:weapon_machinegun",
            "weapon_machinegun",
            Some("q2:ammo_bullets"),
            1,
            30,
            "models/weapons/v_machn/tris.md2",
            "models/weapons/g_machn/tris.md2",
            4,
            3,
            5,
            45,
            49,
            vec![23, 45],
            vec![4, 5],
            true,
        ),
        definition(
            Q2BaseWeaponName::Chaingun,
            "q2:weapon_chaingun",
            "weapon_chaingun",
            Some("q2:ammo_bullets"),
            1,
            60,
            "models/weapons/v_chain/tris.md2",
            "models/weapons/g_chain/tris.md2",
            5,
            4,
            31,
            61,
            64,
            vec![38, 43, 51, 61],
            vec![5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
            true,
        ),
        definition(
            Q2BaseWeaponName::Grenades,
            "q2:ammo_grenades",
            "ammo_grenades",
            Some("q2:ammo_grenades"),
            1,
            2,
            "models/weapons/v_handgr/tris.md2",
            "models/items/ammo/grenades/medium/tris.md2",
            6,
            0,
            15,
            48,
            48,
            vec![29, 34, 39, 48],
            vec![12],
            false,
        ),
        definition(
            Q2BaseWeaponName::Grenadelauncher,
            "q2:weapon_grenadelauncher",
            "weapon_grenadelauncher",
            Some("q2:ammo_grenades"),
            1,
            5,
            "models/weapons/v_launch/tris.md2",
            "models/weapons/g_launch/tris.md2",
            7,
            5,
            16,
            59,
            64,
            vec![34, 51, 59],
            vec![6],
            false,
        ),
        definition(
            Q2BaseWeaponName::Rocketlauncher,
            "q2:weapon_rocketlauncher",
            "weapon_rocketlauncher",
            Some("q2:ammo_rockets"),
            1,
            5,
            "models/weapons/v_rocket/tris.md2",
            "models/weapons/g_rocket/tris.md2",
            8,
            4,
            12,
            50,
            54,
            vec![25, 33, 42, 50],
            vec![5],
            false,
        ),
        definition(
            Q2BaseWeaponName::Hyperblaster,
            "q2:weapon_hyperblaster",
            "weapon_hyperblaster",
            Some("q2:ammo_cells"),
            1,
            30,
            "models/weapons/v_hyperb/tris.md2",
            "models/weapons/g_hyperb/tris.md2",
            9,
            5,
            20,
            49,
            53,
            vec![],
            vec![6, 7, 8, 9, 10, 11],
            true,
        ),
        definition(
            Q2BaseWeaponName::Railgun,
            "q2:weapon_railgun",
            "weapon_railgun",
            Some("q2:ammo_slugs"),
            1,
            5,
            "models/weapons/v_rail/tris.md2",
            "models/weapons/g_rail/tris.md2",
            10,
            3,
            18,
            56,
            61,
            vec![56],
            vec![4],
            false,
        ),
        definition(
            Q2BaseWeaponName::Bfg,
            "q2:weapon_bfg",
            "weapon_bfg",
            Some("q2:ammo_cells"),
            50,
            50,
            "models/weapons/v_bfg/tris.md2",
            "models/weapons/g_bfg/tris.md2",
            11,
            8,
            32,
            55,
            58,
            vec![39, 45, 50, 55],
            vec![9, 17],
            false,
        ),
    ]
}

/// Look up a base weapon definition (`q2WeaponDefinition`).
pub fn weapon_definition(name: Q2BaseWeaponName) -> Q2BaseWeaponDefinition {
    base_weapons()
        .into_iter()
        .find(|definition| definition.name == name)
        .expect("base weapon")
}

/// Look up a weapon definition by classname (`q2WeaponFromClassname`).
pub fn weapon_from_classname(classname: &str) -> Option<Q2BaseWeaponDefinition> {
    base_weapons()
        .into_iter()
        .find(|definition| definition.definition.classname == classname)
}
