#!/usr/bin/env python3
"""THE-860/923 original Q3 MSG/Huff byte oracle; C is developer-only."""
import argparse
import json
import pathlib
import re
import struct
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
PREAMBLE = r'''
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
typedef unsigned char byte;
typedef int qboolean;
typedef struct { int allowoverflow, overflowed, oob; byte *data;
 int maxsize, cursize, readcount, bit; } msg_t;
#define HMAX 256
#define NYT HMAX
#define INTERNAL_NODE (HMAX+1)
typedef struct nodetype { struct nodetype *left,*right,*parent,*next,*prev;
 struct nodetype **head; int weight,symbol; } node_t;
typedef struct { int blocNode,blocPtrs; node_t *tree,*lhead,*ltail,*loc[HMAX+1];
 node_t **freelist; node_t nodeList[768]; node_t *nodePtrs[768]; } huff_t;
typedef struct { huff_t compressor,decompressor; } huffman_t;
#define Com_Memset memset
#define Com_Memcpy memcpy
#define LittleShort(x) (x)
#define LittleLong(x) (x)
#define ERR_DROP 1
#define qtrue 1
#define qfalse 0
void Com_Error(int code,const char *fmt,...) { (void)code;(void)fmt;abort(); }
int oldsize,overflows;
static huffman_t msgHuff;
'''
DRIVER = r'''
int main(int argc,char **argv) {
 Huff_Init(&msgHuff);
 for(int i=0;i<256;i++) for(int j=0;j<msg_hData[i];j++)
  Huff_addRef(&msgHuff.compressor,(byte)i);
 if(argc>1 && !strcmp(argv[1],"codes")) {
  for(int i=0;i<=256;i++) { byte out[16]={0};int bit=0;
   Huff_offsetTransmit(&msgHuff.compressor,i,out,&bit);
   uint32_t value=0;memcpy(&value,out,4);printf("%d %u %d\n",i,value,bit); }
  return 0;
 }
 msgHuff.decompressor=msgHuff.compressor; /* pointer fields still use compressor */
 msgHuff.decompressor.tree=msgHuff.compressor.tree;
 uint32_t count;
 while(fread(&count,4,1,stdin)==1) {
  byte mode; if(fread(&mode,1,1,stdin)!=1 || count>512)return 2;
  byte data[8192]={0},widths[512];uint32_t values[512];
  msg_t msg={.data=data,.maxsize=sizeof(data),.oob=mode==0};
  for(uint32_t i=0;i<count;i++) {
   if(fread(&widths[i],1,1,stdin)!=1 || fread(&values[i],4,1,stdin)!=1)return 3;
   if(mode==1) { for(int b=0;b<widths[i];b++)Huff_putBit((values[i]>>b)&1,data,&msg.bit);
    msg.cursize=(msg.bit+7)/8; }
   else MSG_WriteBits(&msg,(int)values[i],widths[i]);
  }
  /* Original OOB WriteLong advances bit by8 but cursize by4. That unused
     bit counter is not on the wire; report the actual byte cursor here. */
  uint32_t header[2]={(uint32_t)(mode==0?msg.cursize*8:msg.bit),(uint32_t)msg.cursize};
  fwrite(header,4,2,stdout);fwrite(data,1,msg.cursize,stdout);
  msg.bit=msg.readcount=0;
  for(uint32_t i=0;i<count;i++) {
   uint32_t value=0;
   if(mode==1)for(int b=0;b<widths[i];b++)value|=(uint32_t)Huff_getBit(data,&msg.bit)<<b;
   else value=(uint32_t)MSG_ReadBits(&msg,widths[i]);
   fwrite(&value,4,1,stdout);
  }
 }
 return ferror(stdin)?4:0;
}
'''


def function(source, name):
    start = re.search(r"(?:void|int|float)\s+" + name + r"\s*\(", source).start()
    end = source.index("\n}\n", start) + 3
    return source[start:end]


def compile_reference(qsrc, evidence):
    base = qsrc / "quake-iii-arena/code/qcommon"
    msg = (base / "msg.c").read_text()
    huff = re.sub(r'^#include.*$', '', (base / "huffman.c").read_text(), flags=re.M)
    freq = re.search(r'int msg_hData\[256\] = \{.*?\n\};', msg, re.S).group()
    original = huff + freq + function(msg, "MSG_WriteBits") + function(msg, "MSG_ReadBits")
    code = evidence / "original-message.c"
    code.write_text(PREAMBLE + original + DRIVER)
    binary = evidence / "original-message"
    subprocess.run(["cc", "-O2", "-std=c11", str(code), "-o", str(binary)], check=True)
    return binary


def codes(binary):
    rows = [tuple(map(int, line.split())) for line in subprocess.check_output([binary, "codes"], text=True).splitlines()]
    assert len(rows) == 257 and all(n == i for i, (n, _, _) in enumerate(rows))
    assert all(0 < bits <= 32 and value < 1 << bits for _, value, bits in rows)
    text = "// Q3 MSG_initHuffman: unchanged qsrc huffman.c + msg_hData, generated by tools/check_message.py.\n"
    text += "// GPL-2.0-or-later; original id Software Huffman message codes, including NYT.\n"
    text += "pub(super) const CODES: [(u32, u8); 257] = [\n"
    text += ''.join(f"    ({value}, {bits}), // {n}\n" for n, value, bits in rows) + "];\n"
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--qsrc", type=pathlib.Path, default=ROOT.parent / "qsrc")
    parser.add_argument("--evidence", type=pathlib.Path, required=True)
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--probe", type=pathlib.Path)
    args = parser.parse_args()
    args.evidence.mkdir(parents=True, exist_ok=True)
    binary = compile_reference(args.qsrc, args.evidence)
    table = codes(binary)
    target = ROOT / "crates/network/src/message/codes.rs"
    if args.generate:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(table)
    # Rustfmt aligns comments; compare the numeric wire table, not its layout.
    entries = lambda text: re.findall(r'\((\d+),\s*(\d+)\),', text)
    assert entries(target.read_text()) == entries(table), "Q3 message code table differs from original C"
    if args.probe:
        fixture = subprocess.check_output([args.probe, "--fixture"])
        (args.evidence / "fixture.bin").write_bytes(fixture)
        expected = subprocess.check_output([binary], input=fixture)
        actual = subprocess.check_output([args.probe, "--encode"], input=fixture)
        (args.evidence / "original.bin").write_bytes(expected)
        (args.evidence / "rust.bin").write_bytes(actual)
        assert expected == actual, "original C MSG bytes or decoded values differ"
        cursor = cases = fields = 0
        while cursor < len(fixture):
            count = struct.unpack_from('<I', fixture, cursor)[0]
            cursor += 5 + count * 5
            cases += 1
            fields += count
        result = {"cases": cases, "fields": fields, "byte_exact": True, "decoded_values_exact": True,
                  "q3_codes": 257, "original": "Q3 MSG_WriteBits/MSG_ReadBits/Huff unchanged; byte/OOB and raw-bit modes included",
                  "limits": "Synthetic seeded fields; no channel, captures, adaptive connect, live client or gameplay acceptance"}
    else:
        result = {"q3_codes": 257, "table_exact": True}
    (args.evidence / "comparison.json").write_text(json.dumps(result, indent=2) + '\n')
    print(json.dumps(result))


if __name__ == "__main__":
    main()
