#!/usr/bin/env python3
"""Compile the owner CSV into Rust metadata; --check rejects stale output."""
import argparse
import csv
import json
from pathlib import Path
import subprocess
from cvar_catalog import Catalog, COLUMNS, TYPE_NAMES, CONDITIONS, KINDS, OPERATIONS, aliases


def quoted(value):
    return json.dumps(value, ensure_ascii=False)


def enum(prefix, value):
    return prefix + '::' + ''.join(part.title() for part in value.lower().split('_'))


def fields(**values):
    return '{' + ','.join(key + ':' + value for key, value in values.items()) + '}'


def emit(catalog):
    text = catalog.pool_text
    lines = ['// Generated by tools/gen_cvars.py; do not edit.',
             'use crate::catalog::*;', '']

    def array(name, ty, entries, render):
        lines.append(f'pub static {name}: &[{ty}] = &[')
        lines.extend(render(entry) + ',' for entry in entries)
        lines.append('];')

    def span(first, count):
        return f'{first}..{first + count}'

    def row(entry):
        raw, statuses, sources, issues, archive, policies, rule, kind, home, family, not_stored = entry
        names = ('name', 'aliases', 'range_hint', 'owner', 'conversion', 'sources', 'raw_flags')
        source_text = []
        for source in sources:
            default, flags, effect, first_default, first_flags, count_default, count_flags = source
            source_text.append('SourceDefinition' + fields(raw_default=quoted(text(default)),
                raw_flags=quoted(text(flags)), effect=quoted(text(effect)),
                defaults=span(first_default, count_default), flags=span(first_flags, count_flags)))
        return 'Definition' + fields(**dict(zip(names, (quoted(text(x)) for x in raw))),
            audit_status='['+','.join(quoted(text(x)) for x in statuses)+']',
            defaults='['+','.join(source_text)+']', issues=str(issues), archive=str(bool(archive)).lower(),
            policies=str(policies), rule_conversion=str(rule), value_type=enum('ValueType', TYPE_NAMES[kind]),
            home='None' if home == 255 else f'Some({home})', family_count=str(family), stored=str(not not_stored).lower())

    array('DEFINITIONS', 'Definition', catalog.rows, row)
    default_kinds = ('Native', 'Unset', 'StoredOnly', 'Anthology', 'Conditional')
    array('DEFAULTS', 'DefaultClause', catalog.defaults, lambda d: 'DefaultClause'+fields(
        member=quoted(text(d[0])), value=quoted(text(d[1])), condition_text=quoted(text(d[2])),
        raw=quoted(text(d[3])), issues=str(d[4]), kind='DefaultKind::'+default_kinds[d[5]],
        condition=enum('Condition', CONDITIONS[d[6]])))
    array('FLAGS', 'FlagClause', catalog.flags, lambda f: 'FlagClause'+fields(
        member=quoted(text(f[0])), raw=quoted(text(f[1])), bits=str(f[2]), auxiliary=str(f[3]), issues=str(f[4])))
    array('BINDINGS', 'Binding', catalog.bindings, lambda b: 'Binding'+fields(
        name=quoted(text(b[0])), row=str(b[1]), conversions=str(list(b[2])),
        scope='Scope::'+('Any', 'Client', 'Server')[b[3]], canonical=str(bool(b[4])).lower(),
        native_sources=str(b[5]), seat=str(b[6])))
    array('OPERANDS', 'Operand', catalog.operands, lambda op: 'Operand'+fields(
        row=str(op[0]), inverted=str(bool(op[1])).lower(), positive=str(bool(op[2])).lower(),
        unified_bit=str(op[3]), source_bits=str(list(op[4]))))
    array('MAPS', 'EnumMap', catalog.maps, lambda m: 'EnumMap'+fields(
        alias=repr(float(m[0])), canonical=repr(float(m[1])),
        direction='Direction::'+('AliasToCanonical', 'CanonicalToAlias')[m[2]]))
    array('CONVERSIONS', 'Conversion', catalog.conversions, lambda c: 'Conversion'+fields(
        scale=repr(float(c[0])), offset=repr(float(c[1])), lower=repr(float(c[2])), upper=repr(float(c[3])),
        raw=quoted(text(c[4])), operands=span(c[5], c[8]), maps=span(c[6], c[9]), issues=str(c[7]),
        kind=enum('ConversionKind', KINDS[c[10]]), detail=str(bool(c[11])).lower(),
        cgame_only=str(bool(c[12])).lower(), operation=enum('Operation', OPERATIONS[c[13]])))
    # Rustfmt's stable output is compared byte-for-byte; no digest is involved.
    return subprocess.run(['rustfmt', '--emit', 'stdout', '--edition', '2024'],
        input='\n'.join(lines)+'\n', text=True, capture_output=True, check=True).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    with (args.root/'data/unified-cvars.csv').open(encoding='utf-8', newline='') as source:
        reader = csv.DictReader(source)
        if reader.fieldnames != COLUMNS:
            raise ValueError('unexpected canonical CSV columns')
        rows = list(reader)
    if len(rows) != 1260 or any(None in row or any(not value for value in row.values()) for row in rows):
        raise ValueError('expected all nonempty cells of 1260 owner rows')
    names = [row['canonical'].lower() for row in rows]
    if len(set(names)) != len(names) or any(row['type'] not in TYPE_NAMES for row in rows):
        raise ValueError('canonical collision or unknown type hint')
    catalog = Catalog(rows, (args.root/'data/unified-cvars.md').read_text(encoding='utf-8'))
    catalog.build()
    catalog.verify()
    counts = dict(rows=len(rows), aliases=sum(len(aliases(row['aliases'])) for row in rows),
        bindings=len(catalog.bindings), defaults=len(catalog.defaults), flag_clauses=len(catalog.flags),
        conversions=len(catalog.conversions), operands=len(catalog.operands), maps=len(catalog.maps),
        issues=len(catalog.issues))
    outputs = {
        'crates/console/src/cvars_generated.rs': emit(catalog),
        'data/unified-cvars-policy-issues.json': json.dumps(dict(counts=counts, policy_issues=catalog.issues), indent=2, ensure_ascii=False)+'\n',
    }
    for relative, contents in outputs.items():
        path = args.root/relative
        if args.check:
            if not path.exists() or path.read_bytes() != contents.encode('utf-8'):
                raise SystemExit('stale generated file: '+relative)
        else:
            path.write_text(contents, encoding='utf-8')
    print(json.dumps({'checked' if args.check else 'generated': counts}, sort_keys=True))


if __name__ == '__main__':
    main()
