#!/usr/bin/env python3
"""Generate the R0 diagnostic definition from the shared cvar catalog."""
import argparse
import csv
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("catalog", type=Path)
    args = parser.parse_args()
    with args.catalog.open(newline="") as source:
        entries = [row for row in csv.DictReader(source) if row["canonical"] == "developer"]
    if len(entries) != 1:
        raise ValueError("catalog must contain one developer definition")
    row = entries[0]
    if row["aliases"].strip().lower() not in ("", "none") or any(float(row[key]) != 0 for key in (
            "default_q1", "default_qw", "default_q2", "default_q2rr", "default_q3")):
        raise ValueError("developer aliases or defaults changed; review the shared definition")
    output = Path(__file__).resolve().parents[1] / "crates/console/src/cvars_generated.rs"
    output.write_text('''// Generated by tools/generate_cvars.py from the unified cvar catalog.
// R0 registers developer; R2 adds the remaining catalog and string-valued cvars.
use crate::cvars::Definition;

pub static DEFINITIONS: &[Definition] = &[Definition {
    name: "developer",
    aliases: &[],
    default: 0.0,
}];
''')


if __name__ == "__main__":
    main()
